<nav class="navbar navbar-expand-lg menu">
	<div class="container">
		<div class="navbar-nav">
			<a class="menuItem" href="/timeline">
				Home
			</a>

			<a class="menuItem" href="/sair">
				Sair
			</a>
			<img src="/img/twitter_logo.png" class="menuIco" />
		</div>
	</div>
</nav>

<div class="container mt-5">
	<div class="row pt-2">

		<div class="col-md-3">

			<div class="perfil">
				<div class="perfilTopo">

				</div>

				<div class="perfilPainel">

					<div class="row mt-2 mb-2">
						<div class="col mb-2">
							<span class="perfilPainelNome"><?= $this->view->user ?></span>
						</div>
					</div>

					<div class="row mb-2">

						<div class="col">
							<span class="perfilPainelItem">Tweets</span><br />
							<span class="perfilPainelItemValor"><?= $this->view->totalTweets ?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguindo</span><br />
							<span class="perfilPainelItemValor"><?= $this->view->totalSeguindo ?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguidores</span><br />
							<span class="perfilPainelItemValor"><?= $this->view->totalSeguidores ?></span>
						</div>

					</div>

				</div>
			</div>

		</div>

		<div class="col-md-6">
			<div class="row mb-2">
				<div class="col tweetBox">
					<form method="post" action="/tweet">
						<textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="tweet"></textarea>

						<div class="col mt-2 d-flex justify-content-end">
							<button type="submit" class="btn btn-primary">Tweet</button>
						</div>

					</form>
				</div>
			</div>

			<?php foreach ($this->view->tweets as $key => $tweet) { ?>
				<div class="row tweet">
					<div class="col">
						<p><strong><?= $tweet['nome'] ?></strong> <small><span class="text text-muted">- <?= $tweet['data'] ?></span></small></p>
						<p><?= $tweet['tweet'] ?></p>

						<br />
						<?php if ($tweet['id_usuario'] == $_SESSION['id']) { ?>
							<div class="col d-flex justify-content-end">
								<a href="/removerTweet?id_tweet=<?= $tweet['id'] ?>" class="btn btn-danger"><small>Remover</small></a>
							</div>
						<?php } ?>
					</div>
				</div>
			<?php } ?>
			<nav aria-label="Page navigation example">
				<ul class="pagination">

					<?php if($this->view->pagina != 1) { ?>
					<li class="page-item">
						<a class="page-link" href="?pagina=<?=$this->view->pagina - 1?>" aria-label="Previous">
							<span aria-hidden="true">&laquo;</span>
						</a>
					</li>
					<?php }?>

					<?php for($i=1;$i<=$this->view->totPags;$i++){ ?>
						<li class="page-item"><a class="page-link" href="?pagina=<?=$i?>"><?=$i?></a></li>
					<?php } ?>


					<?php if($this->view->pagina != $this->view->totPags) { ?>
						<li class="page-item">
							<a class="page-link" href="?pagina=<?=$this->view->pagina + 1?>" aria-label="Next">
								<span aria-hidden="true">&raquo;</span>
							</a>
						</li>
					<?php }?>

				</ul>
			</nav>

		</div>


		<div class="col-md-3">
			<div class="quemSeguir">
				<span class="quemSeguirTitulo">Quem seguir</span><br />
				<hr />
				<a href="/quemSeguir" class="quemSeguirTxt">Procurar por pessoas conhecidas</a>
			</div>
		</div>

	</div>
</div>